# Copyright 2018 The PDFium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../pdfium.gni")
import("../../testing/test.gni")

source_set("fpdftext") {
  sources = [
    "cpdf_block_builder.cpp",
    "cpdf_block_builder.h",
    "cpdf_column_detector.cpp",
    "cpdf_column_detector.h",
    "cpdf_glyph_extractor.cpp",
    "cpdf_glyph_extractor.h",
    "cpdf_layout_geometry.h",
    "cpdf_layout_types.h",
    "cpdf_line_builder.cpp",
    "cpdf_line_builder.h",
    "cpdf_linkextract.cpp",
    "cpdf_linkextract.h",
    "cpdf_reading_order.cpp",
    "cpdf_reading_order.h",
    "cpdf_spatial_grid.cpp",
    "cpdf_spatial_grid.h",
    "cpdf_table_detector.cpp",
    "cpdf_table_detector.h",
    "cpdf_textblock_detector.cpp",
    "cpdf_textblock_detector.h",
    "cpdf_textpage.cpp",
    "cpdf_textpage.h",
    "cpdf_textpagefind.cpp",
    "cpdf_textpagefind.h",
    "cpdf_word_builder.cpp",
    "cpdf_word_builder.h",
    "unicodenormalizationdata.cpp",
    "unicodenormalizationdata.h",
  ]
  configs += [ "../../:pdfium_strict_config" ]
  deps = [
    "../fpdfapi/font",
    "../fpdfapi/page",
    "../fpdfapi/parser",
    "../fpdfapi/render",
    "../fxcrt",
  ]
  visibility = [ "../../*" ]
}

pdfium_unittest_source_set("unittests") {
  sources = [ "cpdf_linkextract_unittest.cpp" ]
  deps = [ ":fpdftext" ]
  pdfium_root_dir = "../../"
}
